DROP TABLE IF EXISTS STANDARDS;

CREATE TABLE STANDARDS (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    title VARCHAR(250) NOT NULL,
    dok_nr VARCHAR(250) NOT NULL,
    issue_date DATE NOT NULL,
    working_grem VARCHAR(250) DEFAULT NULL,
    working_grem_id VARCHAR(250) DEFAULT NULL
);